### ISSUE TITLE
如果不重定向授权服务器如何能直接把令牌给到第三方软件（小兔）？

### ISSUE THREAD

**Issue by ChenSino** [zq99299/note-book#10]
大佬，关于不使用code这里的内容，如果不重定向授权服务器如何能直接把令牌给到第三方软件（小兔）？
![image](https://user-images.githubusercontent.com/25560521/195240112-24ed4c07-3f7e-4156-92d4-97e579377e91.png)

**Comment by zq99299** [comment]
第 3 步：不是用户给 授权服务说，我同意将权限给 小兔软件么。  同意之后，授权服务这边就可以将 token 回调给 小兔软件了

**Comment by ChenSino** [comment]
> 第 3 步：不是用户给 授权服务说，我同意将权限给 小兔软件么。 同意之后，授权服务这边就可以将 token 回调给 小兔软件了

是的，我的疑惑就是授权服务器在不使用重定向时，如何通过回调的方式把token给到小兔软件呢？

**Comment by ChenSino** [comment]
> > 第 3 步：不是用户给 授权服务说，我同意将权限给 小兔软件么。 同意之后，授权服务这边就可以将 token 回调给 小兔软件了
> 
> 是的，我的疑惑就是授权服务器在不使用重定向时，如何通过回调的方式把token给到小兔软件呢？

就是这个回调是怎么实现的呢？

**Comment by zq99299** [comment]
授权服务 接受的是 用户 认同授权的请求， 肯定是授权服务 回调 小兔软件了。    第一步里面 小兔软件不是引导授权么， 这一步你是不是要在 授权那边  先去备案，比如你微信开发，是不是要搞个 开发账户 之类的。 还要设置 回调通知之类的地址。

**Comment by ChenSino** [comment]
> 

哦对，感谢大佬。
