### ISSUE TITLE
请问elasticsearch相关文档使用的哪个版本讲解的

### ISSUE THREAD

**Issue by qingq0825** [zq99299/note-book#13]
请问elasticsearch相关文档使用的哪个版本讲解的？

**Comment by zq99299** [comment]
你是说  https://zq99299.github.io/note-book/elasticsearch-core/72-employee-example.html#%E7%A4%BA%E4%BE%8B%E7%AE%80%E4%BB%8B
这个 核心和高级吗？
如果是的话 安装里面有说到版本：https://zq99299.github.io/note-book/elasticsearch-core/05-windows-install.html
很老的版本了，笔记内容距离现在也好几年了。
只适合了解，新版肯定有很多不一样了

**Comment by qingq0825** [comment]
感谢哈
