### ISSUE TITLE
请问你的es的高级的参数文章是什么啊

### ISSUE THREAD

**Issue by qq675242356** [zq99299/note-book#20]
你不是说很多没有搞明白吗，我想看看原文在哪里，感觉你的文章写的不错

**Comment by zq99299** [comment]
> 你不是说很多没有搞明白吗，我想看看原文在哪里，感觉你的文章写的不错

没有文章，是视频，我文章里面的内容只会比视频描述内容多

**Comment by qq675242356** [comment]
你在哪里找的视频啊，感觉质量不错

**Comment by qq675242356** [comment]
有视频链接吗

**Comment by zq99299** [comment]
> 有视频链接吗

没有了，作者好像是叫  中华石杉 ，你可以搜下，文章标题基本上就是视频原来的标题

**Comment by qq675242356** [comment]
找到了，满满干货呀，非常感谢
