### ISSUE TITLE
期待大佬补充OAuth 2.0 Pushed Authorization Requests知识

### ISSUE THREAD

**Issue by izanhzh** [zq99299/note-book#22]
- https://www.rfc-editor.org/rfc/rfc9126.html
- https://nestenius.se/net/pushed-authorization-requests-par-in-asp-net-core-9/

**Comment by zq99299** [comment]
感谢你的提供，大概了解了下，原来是解决其中的  授权 URL 携带参数的 安全性问题
近期没有时间，在复习基础知识

**Comment by zq99299** [comment]
准备面试吗这是？ 😄
反正我是

**Comment by izanhzh** [comment]
哈哈哈，在准备了，懂的都懂 😆
