### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by sona0402** [zq99299/note-book#4]
我面试过的人中有在建立上写了 redis、memcached、activemq、zookeeper、kafka、lucene、activiti、爬虫等等，各种技术写了都几十种技术

简历

**Comment by zq99299** [comment]
哈哈哈。 看到了

**Comment by zq99299** [comment]
文章最下面有一个    帮助我们改善此页面！ 的按钮，你点的话，会出现啥情况

**Comment by zq99299** [comment]
此处已修复，在线阅读也同步更新了
